[package]
name = "mesh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
block = { path = "../block" }
env = { path = "../env" }
raft = { path = "../raft" }
types = { path = "../types" }

[dev-dependencies]
proptest.workspace = true
sim = { path = "../sim" }

[lints]
workspace = true
