[package]
name = "mesh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
sim = []

[dependencies]
block = { path = "../block" }
clock = { path = "../clock" }
env = { path = "../env" }
raft = { path = "../raft" }
transport = { path = "../transport" }
types = { path = "../types" }
wire = { path = "../wire" }

[dev-dependencies]
block = { path = "../block", features = ["sim"] }
proptest.workspace = true
sim = { path = "../sim" }

[lints]
workspace = true
