[package]
name = "acceptance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]

[dev-dependencies]
block = { path = "../block" }
connector-influx = { path = "../connector-influx", features = ["sim"] }
env = { path = "../env" }
node = { path = "../node" }
proptest.workspace = true
sim = { path = "../sim" }
types = { path = "../types" }

[lints]
workspace = true
