[package]
name = "connector-modbus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
env = { path = "../env" }
types = { path = "../types" }

[dev-dependencies]
sim = { path = "../sim" }
proptest.workspace = true

[lints]
workspace = true
