[package]
name = "buffer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
block = { path = "../block" }
crc32c = { workspace = true }
env = { path = "../env" }
types = { path = "../types" }

[dev-dependencies]
counting = { path = "../counting" }
proptest = { workspace = true }
sim = { path = "../sim" }

[[test]]
name = "alloc"
harness = false

[lints]
workspace = true
