[package]
name = "config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
document = { path = "../document" }
spec = { path = "../spec" }
types = { path = "../types" }

[lints]
workspace = true

[dev-dependencies]
proptest = { workspace = true }
