[package]
name = "config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
connector = { path = "../connector" }
document = { path = "../document" }
spec = { path = "../spec" }
types = { path = "../types" }

[lints]
workspace = true

[dev-dependencies]
config-hcl = { path = "../config-hcl" }
connector-influx = { path = "../connector-influx" }
proptest = { workspace = true }
