[package]
name = "connector"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]

[dev-dependencies]
counting = { path = "../counting" }
env = { path = "../env" }
proptest = { workspace = true }
sim = { path = "../sim" }
types = { path = "../types" }

[[test]]
name = "alloc"
harness = false

[lints]
workspace = true
