[package]
name = "codec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
types = { path = "../types" }

[dev-dependencies]
divan.workspace = true
proptest.workspace = true

[[bench]]
name = "series"
harness = false
test = true

[lints]
workspace = true
