[package]
name = "node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "foundation"
path = "src/main.rs"

[dependencies]
clock = { path = "../clock" }
env = { path = "../env" }
ops = { path = "../ops" }

[dev-dependencies]
sim = { path = "../sim" }
types = { path = "../types" }

[target.'cfg(loom)'.dependencies]
loom = { workspace = true }

[lints]
workspace = true
