[package]
name = "node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "foundation"
path = "src/main.rs"

[dependencies]
block = { path = "../block" }
buffer = { path = "../buffer" }
clock = { path = "../clock" }
env = { path = "../env" }
estimate = { path = "../estimate" }
home = { path = "../home" }
hub = { path = "../hub" }
ops = { path = "../ops" }
os = { path = "../os" }
types = { path = "../types" }

[dev-dependencies]
codec = { path = "../codec" }
counting = { path = "../counting" }
proptest = { workspace = true }
sim = { path = "../sim" }

[target.'cfg(loom)'.dependencies]
loom = { workspace = true }

[lints]
workspace = true
