[package]
name = "spec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
types = { path = "../types" }
blake3 = { version = "1.8.7", default-features = false }

[dev-dependencies]
proptest = { version = "1.11.0", default-features = false, features = ["std"] }

[lints]
workspace = true
