[package]
name = "connector-ni"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
libloading.workspace = true
types = { path = "../types" }

[dev-dependencies]
connector-ni-stub = { path = "../connector-ni-stub" }

[lints]
workspace = true
