[package]
name = "clock"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
env = { path = "../env" }
estimate = { path = "../estimate" }
ring = { path = "../ring" }
types = { path = "../types" }
wire = { path = "../wire" }

[dev-dependencies]
counting = { path = "../counting" }
divan = { workspace = true }
proptest = { workspace = true }
sim = { path = "../sim" }

[[bench]]
name = "reader"
harness = false

[[test]]
name = "alloc"
harness = false

[lints]
workspace = true
