[package]
name = "connector-opcua"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
open62541 = ["dep:cc", "dep:env", "dep:types"]

[dependencies]
env = { path = "../env", optional = true }
types = { path = "../types", optional = true }

[build-dependencies]
cc = { workspace = true, optional = true }

[dev-dependencies]
cc = { workspace = true }
env = { path = "../env" }
proptest.workspace = true
sim = { path = "../sim" }
types = { path = "../types" }

[lints]
workspace = true
