[package]
name = "connector-opcua"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
open62541 = ["dep:cc"]

[build-dependencies]
cc = { workspace = true, optional = true }

[dev-dependencies]
cc = { workspace = true }

[lints]
workspace = true
