[package]
name = "connector-influx"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
sim = [
    "dep:bytes",
    "dep:connector",
    "connector/sim",
    "dep:env",
    "dep:http",
    "dep:influxdb-line-protocol",
]

[dependencies]
bytes = { workspace = true, optional = true }
connector = { path = "../connector", optional = true }
env = { path = "../env", optional = true }
http = { workspace = true, optional = true }
influxdb-line-protocol = { workspace = true, optional = true }
types = { path = "../types" }

[dev-dependencies]
connector = { path = "../connector" }
proptest.workspace = true
sim = { path = "../sim" }

[lints]
workspace = true
