[package]
name = "connector-influx"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
sim = [
    "dep:bytes",
    "connector/sim",
    "dep:env",
    "dep:influxdb-line-protocol",
]

[dependencies]
bytes = { workspace = true, optional = true }
connector = { path = "../connector" }
document = { path = "../document" }
env = { path = "../env", optional = true }
http.workspace = true
influxdb-line-protocol = { workspace = true, optional = true }
types = { path = "../types" }
unicode-properties.workspace = true

[dev-dependencies]
counting = { path = "../counting" }
env = { path = "../env" }
proptest.workspace = true
sim = { path = "../sim" }

[[test]]
name = "memory"
harness = false
required-features = ["sim"]

[lints]
workspace = true
