[package]
name = "blob"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
block = { path = "../block" }
env = { path = "../env" }
types = { path = "../types" }

[dev-dependencies]
block = { path = "../block", features = ["sim"] }
sim = { path = "../sim" }

[lints]
workspace = true
