[package]
name = "home"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
block = { path = "../block" }
codec = { path = "../codec" }
control = { path = "../control" }
delivery = { path = "../delivery" }
types = { path = "../types" }

[dev-dependencies]
proptest = { workspace = true }

[lints]
workspace = true
